# Generated by Django 4.0.1 on 2022-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('matches_played', models.IntegerField()),
                ('rounds_won_by_t', models.IntegerField()),
                ('rounds_won_by_ct', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
