# Generated by Django 4.0.1 on 2022-01-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='rounds_won_by_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='rounds_won_by_t',
            field=models.IntegerField(default=0),
        ),
    ]
