# Generated by Django 4.0.1 on 2022-02-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userinformation_profile_image_url'),
        ('tournament', '0002_alter_map_matches_played_alter_map_rounds_won_by_ct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_won_by_team_a', models.IntegerField(default=0, verbose_name='Rounds won by Team A')),
                ('rounds_won_by_team_b', models.IntegerField(default=0, verbose_name='Rounds won by Team B')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.map')),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_a', to='users.team', verbose_name='Team A')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_b', to='users.team', verbose_name='Team B')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_winner', to='users.team')),
            ],
        ),
    ]
