# Generated by Django 4.0.1 on 2022-02-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userinformation_profile_image_url'),
        ('tournament', '0003_mapscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapscore',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='mapscore',
            name='team_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_a', to='users.team', verbose_name='Team A'),
        ),
        migrations.AlterField(
            model_name='mapscore',
            name='team_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_b', to='users.team', verbose_name='Team B'),
        ),
        migrations.AlterField(
            model_name='mapscore',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_winner', to='users.team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('banning', 'Banning phase'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30)),
                ('type', models.CharField(choices=[('not_determined', 'Not determined'), ('bo1', 'Best of One'), ('bo2', 'Best of Two'), ('bo3', 'Best of Three'), ('bo5', 'Best of Five')], default='not_determined', max_length=30)),
                ('map_scores', models.ManyToManyField(to='tournament.MapScore')),
                ('maps', models.ManyToManyField(to='tournament.Map')),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_a', to='users.team', verbose_name='Team A')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_b', to='users.team', verbose_name='Team B')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_winner', to='users.team')),
            ],
        ),
    ]
