# Generated by Django 4.0.1 on 2022-02-12 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_team_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0004_alter_mapscore_options_alter_mapscore_team_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('sponsor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='maps',
            field=models.ManyToManyField(blank=True, to='tournament.Map'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('not_determined', 'Not determined'), ('single_elimination', 'Single elimination'), ('league', 'League (all vs. all)'), ('combined', 'Combined')], default='not_determined', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('removed', 'Removed')], default='scheduled', max_length=30)),
                ('private', models.BooleanField(default=False)),
                ('starting_date', models.DateField()),
                ('available_maps', models.ManyToManyField(to='tournament.Map')),
                ('creator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(to='tournament.Game')),
                ('prizes', models.ManyToManyField(to='tournament.Prize')),
                ('teams', models.ManyToManyField(to='users.Team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_team_winner', to='users.team')),
            ],
        ),
    ]
