# Generated by Django 4.0.1 on 2022-02-12 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0005_prize_alter_game_maps_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
