# Generated by Django 4.0.1 on 2022-02-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_prize_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='starting_date',
            field=models.DateTimeField(),
        ),
    ]
