# Generated by Django 4.0.1 on 2022-02-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team_members_alter_team_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='profile_image_url',
        ),
    ]
